### PR TITLE
Add the -r flag for requirements.txt

### PR DESCRIPTION
**Pull request by carise**

### CODE REVIEW

**Comment by carise** [comment]
Not sure why the Travis build keeps failing. Any ideas?

**Comment by EricBeach** [comment]
I *think* the root problem from below is that the ``./travis/jekyll_build.sh`` script is checking the URLs linked to from the website and it is unable to get a valid response from https://www.gcppodcast.com/post/episode-120-forseti-with-nenad-stojanovski-and-andrew-hoying/ which is causing the ``./travis/jekyll_build.sh`` script to fail, which causes the Travis operation to fail.
Perhaps the Docker container does not have certs and so the request to https://www.gcppodcast.com/post/episode-120-forseti-with-nenad-stojanovski-and-andrew-hoying/  is failing with ``Peer certificate cannot be authenticated with given CA certificates``


```bash
Checking 243 external links...
Ran on 189 files!
- ./_www/www/news/index.html
  *  External link https://www.gcppodcast.com/post/episode-120-forseti-with-nenad-stojanovski-and-andrew-hoying/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Peer certificate cannot be authenticated with given CA certificates
htmlproofer 3.9.2 | Error:  HTML-Proofer found 1 failure!
The command "./travis/jekyll_build.sh" exited with 1.
```

**Comment by carise** [comment]
@EricBeach thanks Eric, I took a look at some of the previous doc PRs and noticed they built successfully. Any idea why things are different this time?

**Comment by EricBeach** [comment]
I just ran ``./travis/jekyll_build.sh`` on GCE machine and got the same error as Travis is reporting.

When I run ``curl -v https://www.gcppodcast.com/post/episode-120-forseti-with-nenad-stojanovski-and-andrew-hoying/``from that machine, I get a certificate error. If I run ``curl -v https://www.gcppodcast.com/post/episode-120-forseti-with-nenad-stojanovski-and-andrew-hoying/`` from my local machine, everything works fine.


```bash
$ curl -v https://www.gcppodcast.com/post/episode-120-forseti-with-nenad-stojanovski-and-andrew-hoying/
*   Trying 74.125.26.121...
* TCP_NODELAY set
* Connected to www.gcppodcast.com (74.125.26.121) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by blueandgold** [comment]
The link is that the html-proofer is complaining about is working.  Opening #1881 to resolve this, so this can be merged.

**Pull request merged**
