### PR TITLE
Setup, Docker, and requirements.txt improvements

### PR DESCRIPTION
**Pull request by mirons-google**
This PR does a few things

- Cleans up the top-level directory structure by putting the Dockerfile in docker-files/ with a requirements.txt
- Requirements.txt build on each other and ultimately feed from setup.py, this allows us to not have pip packages defined in multiple places. That one place is now setup.py!!
- Move the setup wizard out of scripts and into setup as well as create stubs for it so a user can run `python setup.py install; forseti_setup`
- Removal of coveralls for coverage, codecov is now the default
- Enable pylint checking on setup/

### CODE REVIEW

**Comment by carise** [comment]
Could you also update the deployment templates to reflect the setup?

Also, just wondering if you think our documentation needs to be adjusted, now that the user is installing code before they can access the setup wizard. That means we don't "share" the same prerequisites.

**Comment by mirons-google** [comment]
@carise what exactly are the changes needed for the deployment templates?

**Comment by carise** [comment]
If you could make sure the startup script works properly, using this branch.

I also noticed that protos are not getting built during the setup process:

```
$ forseti_enforcer
Traceback (most recent call last):
  File "/Users/carise/.virtualenvs/forseti-temp/bin/forseti_enforcer", line 11, in <module>
    load_entry_point('forseti-security==1.0.2', 'console_scripts', 'forseti_enforcer')()
  File "/Users/carise/.virtualenvs/forseti-temp/lib/python2.7/site-packages/forseti_security-1.0.2-py2.7.egg/google/cloud/security/stubs.py", line 40, in RunForsetiEnforcer
    import google.cloud.security.enforcer.enforcer as forseti_enforcer
  File "/Users/carise/.virtualenvs/forseti-temp/lib/python2.7/site-packages/forseti_security-1.0.2-py2.7.egg/google/cloud/security/enforcer/enforcer.py", line 34, in <module>
    from google.cloud.security.enforcer import batch_enforcer
  File "/Users/carise/.virtualenvs/forseti-temp/lib/python2.7/site-packages/forseti_security-1.0.2-py2.7.egg/google/cloud/security/enforcer/batch_enforcer.py", line 26, in <module>
    from google.cloud.security.enforcer import enforcer_log_pb2
ImportError: cannot import name enforcer_log_pb2
```

**Comment by blueandgold** [comment]
Adding `cla: yes` label, as the PR author is a googler at the time of this PR was created.

**Pull request closed without merging**
