### PR TITLE
Added /develop/reference as part of files to ignore

### PR DESCRIPTION
**Pull request by joecheuk**

### CODE REVIEW

**Comment by mirons-google** [comment]
This likely becomes:

```shell
 --url-ignore "/GoogleCloudPlatform/forseti-security/edit/" \
 --url-ignore "/develop/reference/" \
./_www/www
```

**Comment by joecheuk** [comment]
```
 --url-ignore "/GoogleCloudPlatform/forseti-security/edit/" \
 --url-ignore "/develop/reference/" \
./_www/www

```
Doesn't seem to be working.

Based on this issue it seems like it only supports comma separated, let me update it with comma and see if that helps.
https://github.com/gjtorikian/html-proofer/issues/377

**Comment by joecheuk** [comment]
@mirons-google Updated using file-ignore flag, PTAL!

**Review by salwa445 — COMMENTED** [review]
R

**Pull request merged**
