### PR TITLE
clear DBs

### PR DESCRIPTION
**Pull request by angelomellos**
This is for issue https://github.com/GoogleCloudPlatform/forseti-security/issues/438

It lets the user add a flag to drop all DB tables from previous inventory runs before running the current one. Like this:
forseti_inventory -clear_previous

Redone to change the Git email so the CLA will be signed.

### CODE REVIEW

**Comment by blueandgold** [comment]
Thanks for submitting this PR!  But before we accept it, can we have a discussion first for all the possible use cases, so that we have a coherent way for purging the tables?  Since this is the start of a long weekend, will follow-up with you next week.  Thanks again!

**Comment by angelomellos** [comment]
Ok sure, sounds good.

**Comment by victorvess** [comment]
@angelomellos I was starting to look into an approach for this as well, I am wondering instead of deleting every single table in the database, should we allow a retention time interval and base the deletes on a query of **snapshot_cycles** table.  Do you think that would meet your needs?  I was going to start to work my own branch/PR, maybe we can reconcile them?

**Comment by blueandgold** [comment]
@angelomellos, there is a proposal by @victorvess to handle this in a more flexible and comprehensive way in issue #438 .  Can you please take a look?

**Comment by angelomellos** [comment]
Sounds like a good idea to me.

**Comment by blueandgold** [comment]
@angelomellos, PR #1129 has been merged and will cover your use case here, i.e. use ```retention_days = 0```  So, I am going to close out this PR.  Thanks for motivating the work here!

**Pull request closed without merging**
