### PR TITLE
Improving Gitignore

### PR DESCRIPTION
**Pull request by mirons-google**
Adding an entry for possible cloud credentials.

### CODE REVIEW

**Comment by mirons-google** [comment]
Sorry this was suppose to be all .json files in the top-level directory. Is there a better pattern?

**Comment by carise** [comment]
Then the line should be

/*.json

which will only ignore json files in the toplevel directory.

**Comment by mirons-google** [comment]
done, thanks!

**Comment by blueandgold** [comment]
Adding `cla: yes` label, as the PR author is a googler at the time of this PR was created.

**Pull request merged**
