### PR TITLE
adding Michael Capicotto as a contributor

### PR DESCRIPTION
**Pull request by mcapts**
Adding myself as a contributor, in the CONTRIBUTORS file.

### CODE REVIEW

**Comment by blueandgold** [comment]
@mcapts Can you please add `I signed it!` to make the CLA bot happy?

**Comment by mcapts** [comment]
I signed it!

**Comment by mcapts** [comment]
I signed it!

**Comment by blueandgold** [comment]
@googlebot rescan

**Comment by blueandgold** [comment]
Adding `cla: yes` label, as the PR author has ack'd signing the CLA.

**Pull request merged**
