### PR TITLE
Forseti Day 19 schedule as image

### PR DESCRIPTION
**Pull request by ryanismert**
Replacing the markdown table in the Forseti Day news post with an image for readability.

### CODE REVIEW

**Comment by mirons-google** [comment]
@ryanismert here's an example of how to include an image in the markdown of a news post.

https://raw.githubusercontent.com/GoogleCloudPlatform/forseti-security/0f46081ee26b8e63052dc3744f315f2ab28a36b0/_news/2018-05-09-test-post.md

**Comment by ryanismert** [comment]
@mirons-google I cut and paste the Jekyl template from the visualization post - do you believe it won't work, or that an  tag is superior?

**Comment by mirons-google** [comment]
Apologies, it'll work. If you want the image to be included in the snippet of all news then you'll want to use the excerpt front-matter field.

**Comment by red2k18** [comment]
@ryanismert

**Comment by red2k18** [comment]
This is how Jekyll renders the Markdown in the .md file. Let me know if you want to make any changes  before I push it out.

image

**Comment by ryanismert** [comment]
lgtm, thanks @red2k18

**Pull request merged**
